### PR TITLE
Restore scroll position after reload

### LINKED ISSUE #1: Restore scroll position after reload

### PR DESCRIPTION
**Pull request by mikker**
Saves scroll position after scroll events and restores it after updates. Hat tip to @tomazzlender's [implementation](https://github.com/kirillplatonov/hotwire-livereload/issues/1#issuecomment-1198648012).

Spent way too long debugging an issue where it would reset without a scroll event. Turned out I had two windows open setting each their own scroll value. So that's sort of a thing but not sure it's something we can fix.

* Do we want this to be togglable with a config option?

Closes #1

### CODE REVIEW

**Comment by tomazzlender** [comment]
Thanks for putting effort into the PR! ❤️

> Do we want this to be togglable with a config option?

That would be sweet. I noticed that sometimes I need to turn it off due to some circumstances, perhaps others will find themselves in such situations too and will welcome the option.

**Comment by mikker** [comment]
@kirillplatonov Still using this fork in my app and I don't seem to have any critical issues. Can we merge it and release?

**Comment by kirillplatonov** [comment]
Hey @mikker. Thank you for that PR and sorry for delay with review. It looks and works great. I will publish v1.3 with this feature shortly.

**Comment by timteske** [comment]
Hi, do i need to enable this functionality or need to configure something?
Find the Error, i use turbo_stream as reload_method. Using the default fixed my problem.
Thanks for this Epic Feature!

**Comment by kirillplatonov** [comment]
No need to enable anything. It should work out of the box in `v1.3.0`.

**Comment by Intrepidd** [comment]
This PR causes an issue for me : each time I click on a link, the scroll resets to 0 before the next page is loaded.

This seems to be because the click event resets scroll to 0, and then the `turbo:before-visit` event restore the scroll position, so to 0.

**Comment by Intrepidd** [comment]
Shouldn't we use `turbo:visit` event rather than `turbo:click` ? to make sure we reset the scroll position after and not before the visit has occured ? Happy to open a PR if that sounds like a good solution

**Pull request merged**
